# appveyor.yml
version: 1.0.0.{build}

platform: x64

branches:
  only:
    - master

clone_folder: c:\gopath\src\github.com\Fancman\BackupSoftware

environment:
  GOPATH: c:\gopath

install:
  - ps: Start-FileDownload "https://www.dropbox.com/s/2ps67souqun8i29/7-ZipPortable.zip?dl=0" -FileName 7-ZipPortable.zip;
  - cmd: 7z x 7-ZipPortable.zip -o%WXWIN% > null

before_build:
  - echo %PATH%
  - echo %GOPATH%
  - set PATH=%GOPATH%\bin;C:\msys64\mingw64\bin;c:\go\bin;%PATH%
  - go version
  - go env
  - go get ./...

build_script:
  - go build -o buildOutput\myapp -i .
