# appveyor.yml
version: 1.0.0.{build}

platform: x64

branches:
  only:
    - master

clone_folder: c:\gopath\src\github.com\Fancman\BackupSoftware

environment:
  GOPATH: c:\gopath

install:
  - ps: Start-FileDownload "https://www.dropbox.com/s/2ps67souqun8i29/7-ZipPortable.zip?dl=1" -FileName 7-ZipPortable.zip;
  - cmd: mkdir 7-ZipPortable
  - cmd: 7z x 7-ZipPortable.zip -o%clone_folder%\7-ZipPortable

before_build:
  - echo %PATH%
  - echo %GOPATH%
  - set PATH=%GOPATH%\bin;C:\msys64\mingw64\bin;c:\go\bin;%PATH%
  - go version
  - go env
  - dir
  #- cmd: cd %clone_folder%\7-ZipPortable && dir
  - go get ./...

build_script:
  - go build -o buildOutput\myapp.exe -i .


  # Artifacts Configuration    #
artifacts: # push all files in directory
  path: buildOutput\*.exe
  name: installer
# Deploy to GitHub Releases
  
deploy:
  release: myproduct-v$(APPVEYOR_BUILD_VERSION)
  description: 'Release description'
  provider: GitHub
  auth_token:
    secure: awRHVY0L1MODweHZoCISezWyO9AfhKElTWorVXCw1oMi6KXKvQqH8TFtO6YqCrpK # your encrypted token from GitHub
  artifact: installer # upload all NuGet packages to release assets
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
  #  APPVEYOR_REPO_TAG: true        # deploy on tag push only